# Generated by Django 2.0.3 on 2018-07-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
