# Generated by Django 2.0.3 on 2018-07-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='worked',
            field=models.BooleanField(default=False),
        ),
    ]
